Repository RenaldMorino/oxygencs-grp1-eq5, pull requests merged in 2024-07, with the labels that each got.

#15 Ajout du build&push de l'image docker (une fois merge sur main)
  .github/workflows/ci.yml
Labels: enhancement

#17 Fix attempts to skipped build&publish image job
  .github/workflows/ci.yml
Labels: bug

#19 Fix attempts to skipped build&publish image job v2
  .github/workflows/ci.yml
  .github/workflows/docker.yml
Labels: bug

#20 fixed typo in docker login-action
  .github/workflows/docker.yml
Labels: bug

#25 Fixed COPY command in wrong order + image size reduce
  .dockerignore
  Dockerfile
Labels: bug

#27 Added latest and versionned tags for Docker images
  .github/workflows/docker.yml
Labels: enhancement, coding

#21 #3 - Add Database connection system and #4 - Save the HVAC data in the database
  .gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  src/main.py
Labels: enhancement

#29 Fixed psycopg2 library not able to install with pipenv
  Pipfile
  Pipfile.lock
Labels: bug

#37 Added the Kubernetes config map for oxygencs
  infra/configMap.yaml
Labels: documentation, coding

#36 Added the Kubernetes secrets for oxygencs
  README.md
  infra/secrets.yaml
Labels: documentation, coding

#38 Added deployment of oxygencs
  .dockerignore
  infra/configMap.yaml
  infra/deployment.yaml
Labels: documentation, coding
